apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: quay.io/dsanchor/quarkus-petclinic
  newName: image-registry.openshift-image-registry.svc.cluster.local:5000/rruizher/quarkus-petclinic
  newTag: c1b7b7e65b54d73ae28c0dd73c71f8fbdc52ed0e
